---
title: "Data model report"
date: '`r Sys.Date()`'
output:
  html_document:
    toc: true
params:
    tables: ""
    model: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(AnvilDataModels)
library(dplyr)
```

```{r}
tables <- params$tables
model <- json_to_dm(params$model)
return_value <- TRUE # returned to render function to indicate T/F passing checks
```

Data model version: `r attr(model, "data_model_version")`

## Required columns

```{r}
chk <- check_column_names(tables, model)
res <- parse_column_name_check(chk)
if (nrow(res) > 0) {
    knitr::kable(res)
} else {
    cat("All column names match data model.")
}
if (length(unlist(lapply(chk, function(x) x$missing_required_columns))) > 0) return_value <- FALSE
```

```{r}
chk <- check_missing_values(tables, model)
res <- parse_column_type_check(chk)
if (nrow(res) > 0) {
    return_value <- FALSE
    knitr::kable(res)
} else {
    cat("No missing values in required columns.")
}
```

## Column types

```{r}
chk <- check_column_types(tables, model)
res <- parse_column_type_check(chk)
if (nrow(res) > 0) {
    return_value <- FALSE
    knitr::kable(res)
} else {
    cat("All column types match data model.")
}
```
